name: code-coverage

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  unittest-cov:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Rust (cache & toolchain)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run unittest with coverage
        run: |
          cargo install grcov
          cargo clean
          RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests" cargo +stable test --no-fail-fast
          grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing -o ./lcov.info
        env:
          RUSTUP_TOOLCHAIN: stable

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./lcov.info
